apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client-api
  namespace: mongo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client-api
  template:
    metadata:
      labels:
        app: mongo-client-api
    spec:
      containers:
      - name: mongo-client
        image: ghcr.io/akinanny/mongo-client:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-client-api
  namespace: mongo-system
spec:
  type: NodePort
  selector:
    app: mongo-client-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
